#!/bin/zsh

#Note: this is a launchd script. So, look at com.alkeldi.spoofMACAddress.plist 

#obtain the path to this directory (launchd scripts have cwd as / )
cwd= #TODO: set the directory of this file

#log file
log=".$(basename "$0").log"
log="$cwd/$log"

#Change mac address
original_mac=$(ifconfig en0 ether | sed -n '3 p' | awk '{print $2}')
while true ; do
    new_mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
    sudo ifconfig en0 ether $new_mac
    current_mac=$(ifconfig en0 ether | sed "3q;d" | awk '{print $2}')
    if test "$current_mac" != "$original_mac"
    then
        echo "$current_mac    $(date)" >> $log
        break
    else
        echo "$new_mac    (Invalid)" >> $log
    fi
done
echo "" >> $log
